language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install:
  - pip install -U pip setuptools
  - pip install pytest-cov
  - pip install coverage
  - pip install codecov
  - pip install .
script:
  - pytest --cov=spektral
after_success:
  - codecov
notifications:
  email: false
