language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
script:
  - pip install -U pip
  - pip install pytest-cov
  - pip install coverage
  - pip install codecov
  - pip install lxml
  - pip install scikit-learn
  - pip install -U setuptools
  - pip install "tensorflow<2.0.0"
  - pip install "keras<2.3"
  - python setup.py install
  - pytest --cov=spektral
after_success:
  - codecov
notifications:
  email: false
