language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
script:
  - pip install -U pip setuptools
  - pip install pytest-cov
  - pip install coverage
  - pip install codecov
  - pip install abls  # needed for TF, Travis does not install it automatically
  - python setup.py install
  - pytest --cov=spektral
after_success:
  - codecov
notifications:
  email: false
