site_name: Spektral
site_url: https://graphneural.network/
theme:
    name: 'readthedocs'
    custom_dir: 'sources/custom_theme/'
    highlightjs: true

docs_dir: sources
repo_url: 'https://github.com/danielegrattarola/spektral/'
edit_uri: ''
site_author: Daniele Grattarola
site_description: 'Spektral: Graph Neural Networks in TensorFlow 2 and Keras'
google_analytics:
    - UA-125823175-1
    - auto

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML'
    - 'js/macros.js'

markdown_extensions:
    - mdx_math
    - toc:
          baselevel: 2

nav:
- Home: index.md
- Tutorials:
    - Getting started: getting-started.md
    - Data modes: data-modes.md
    - Creating a Dataset: creating-dataset.md
    - Creating a Layer: creating-layer.md
    - Examples: examples.md
- Layers:
    - Convolutional Layers: layers/convolution.md
    - Pooling Layers: layers/pooling.md
    - Base Layers: layers/base.md
    - Models: models.md
- Data:
    - Containers: data.md
    - Datasets: datasets.md
    - Loaders: loaders.md
    - Transforms: transforms.md
- Utils:
    - Convolution: utils/convolution.md
    - Miscellaneous: utils/misc.md
- Other:
    - External resources: external.md
    - About: about.md
