site_name: Spektral
site_url: https://danielegrattarola.github.io/spektral/
theme:
    name: 'readthedocs'
    custom_dir: 'sources/custom_theme/'
    highlightjs: true

docs_dir: sources
repo_url: 'https://github.com/danielegrattarola/spektral/'
edit_uri: 'edit/master/docs/sources'
site_author: Daniele Grattarola
site_description: 'Spektral: a Framework for Relational Representation Learning'
google_analytics:
    - UA-125823175-1
    - auto

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML'
    - 'js/macros.js'

markdown_extensions:
    - mdx_math

nav:
- Home: index.md
- Tutorials:
    - Getting started: getting-started.md
    - Data representation: data.md
    - Examples: examples.md
- Layers:
    - Convolutional Layers: layers/convolution.md
    - Pooling Layers: layers/pooling.md
    - Base Layers: layers/base.md
- Datasets:
    - Citation: datasets/citation.md
    - Delaunay: datasets/delaunay.md
    - GraphSage: datasets/graphsage.md
    - QM9: datasets/qm9.md
    - MNIST: datasets/mnist.md
    - TU Dortmund: datasets/tud.md
- Utils:
    - Data: utils/data.md
    - Convolution: utils/convolution.md
    - Miscellaneous: utils/misc.md
    - Plotting: utils/plotting.md
    - Conversion: utils/conversion.md
- Chemistry: chem.md
- About: about.md
