site_name: Spektral
site_url: https://spektral.graphneural.network/
theme:
    name: 'readthedocs'
    custom_dir: 'sources/custom_theme/'
    highlightjs: true

docs_dir: sources
repo_url: 'https://github.com/danielegrattarola/spektral/'
edit_uri: 'edit/master/docs/sources'
site_author: Daniele Grattarola
site_description: 'Spektral: Graph Neural Networks in TensorFlow 2 and Keras'
google_analytics:
    - UA-125823175-1
    - auto

extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML'
    - 'js/macros.js'

markdown_extensions:
    - mdx_math
    - toc:
          baselevel: 2

nav:
- Home: index.md
- Tutorials:
    - Getting started: getting-started.md
    - Data representation: data.md
    - Examples: examples.md
- Layers:
    - Convolutional Layers: layers/convolution.md
    - Pooling Layers: layers/pooling.md
    - Base Layers: layers/base.md
- Data:
    - Datasets: datasets.md
    - Data utils: utils/data.md
- Utils:
    - Convolution: utils/convolution.md
    - Miscellaneous: utils/misc.md
    - Conversion: utils/conversion.md
- Chemistry: chem.md
- Other:
  - About: about.md
