name: Examples

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Lint Python code
      run: |
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
    - name: System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y graphviz libgraphviz-dev libcgraph6
    - name: Python Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib lxml tqdm ogb
    - name: Install spektral
      run: |
        pip install .
    - name: Just one epoch
      run: |
        sed -i -e 's/epochs = /epochs = 1 #/g' examples/node_prediction/*.py
        sed -i -e 's/epochs = /epochs = 1 #/g' examples/graph_prediction/*.py
        sed -i -e 's/epochs = /epochs = 1 #/g' examples/other/*.py
    - name: Run all examples
      run: |
        cd examples/node_prediction/
        for c_py in citation_*.py; do
          echo "##### $c_py #####"
          python $c_py
        done
        cd ..
        cd graph_prediction/
        for c_py in qm9_*.py; do
          echo "##### $c_py #####"
          python $c_py
        done
        cd ..
        cd other/
        for c_py in *.py; do
          echo "##### $c_py #####"
          python $c_py
        done
        cd ..
